### PR TITLE
Release v2.31.5+rev1

### PR DESCRIPTION
**Pull request by floion**

### CODE REVIEW

**Comment by floion** [comment]
@resin-jenkins test this please

**Comment by floion** [comment]
@resin-ci retest

**Comment by nazrhom** [comment]
@resin-ci retest

**Comment by floion** [comment]
@resin-jenkins test this please

**Comment by nazrhom** [comment]
@resin-ci retest

**Comment by floion** [comment]
@resin-ci retest

**Comment by nazrhom** [comment]
@resin-ci retest

**Pull request merged**
