### PR TITLE
Update autohat to v0.0.12

### PR DESCRIPTION
**Pull request by ZubairLK**

### CODE REVIEW

**Comment by floion** [comment]
@ZubairLK the devices PRs do not use `Change-type` and instead use `Changelog-entry`

**Comment by floion** [comment]
@horia-delicoti @telphan https://jenkins.dev.resin.io/job/yocto-qemux86/4126/console failed because there is no `resin sync` anymore. And this should also now be switched from `resin` to `balena` cli commands

**Comment by ZubairLK** [comment]
@resin-jenkins retest this please

**Comment by ZubairLK** [comment]
@resin-jenkins

**Comment by ZubairLK** [comment]
@resin-jenkins retest this please

**Comment by ZubairLK** [comment]
@balena-ci retest

**Pull request merged**
