### PR TITLE
layers/meta-balena: update to 2.58.6

### PR DESCRIPTION
**Pull request by jakogut**
Update meta-balena from 2.50.1 to 2.58.6

Fixes a build issue with openvpn in do_package_qa. An error is raised
because the package requires bash, but it isn't listed in RDEPENDS.

Fixed in f84dcfd.

Signed-off-by: Joseph Kogut <joseph@balena.io>

### CODE REVIEW

**Review by alexgg — APPROVED** [review]
lgtm

**Comment by alexgg** [comment]
@balena-ci retest

**Comment by floion** [comment]
@jakogut you also need the proper Changelog-entry. See https://github.com/balena-os/balena-qemu/commit/853ae84ed422ee6004bdd63f2072f6b98effebf5 for example

**Comment by jakogut** [comment]
> @jakogut you also need the proper Changelog-entry. See [853ae84](https://github.com/balena-os/balena-qemu/commit/853ae84ed422ee6004bdd63f2072f6b98effebf5) for example

@floion The commit and PR documentation in [process](https://github.com/balena-io/process/blob/master/process/Commit_and_PR_Guidelines.md) says:

> Commits marked with the Change-type tag will have their subject added as an entry in the generated CHANGELOG.md. If you want to override this default behavior and add your own changelog entry instead, you can use the optional Changelog-Entry: <custom changelog entry> tag in Change-type-tagged commits.

Can you clarify when Change-type is optional, and when it is required? Should the documentation be updated?

For that matter, my commit is also missing the Change-type footer, as is the commit you linked. Is this required?

Thanks!

**Comment by floion** [comment]
> > @jakogut you also need the proper Changelog-entry. See [853ae84](https://github.com/balena-os/balena-qemu/commit/853ae84ed422ee6004bdd63f2072f6b98effebf5) for example
> 
> @floion The commit and PR documentation in [process](https://github.com/balena-io/process/blob/master/process/Commit_and_PR_Guidelines.md) says:
> 
> > Commits marked with the Change-type tag will have their subject added as an entry in the generated CHANGELOG.md. If you want to override this default behavior and add your own changelog entry instead, you can use the optional Changelog-Entry:  tag in Change-type-tagged commits.
> 
> Can you clarify when Change-type is optional, and when it is required? Should the documentation be updated?
> 
> For that matter, my commit is also missing the Change-type footer, as is the commit you linked. Is this required?
> 
> Thanks!

@jakogut the Change-type is not needed for the device type repos. Maybe we should update the process docs to reflect this.

**Comment by floion** [comment]
@resin-jenkins add to whitelist

**Pull request merged**
