### PR TITLE
Update autohat to v0.0.9

### PR DESCRIPTION
**Pull request by ZubairLK**
Changes the Dockerfile base image from jessie to stretch

### CODE REVIEW

**Comment by floion** [comment]
@resin-jenkins add to whitelist

**Comment by ZubairLK** [comment]
@resin-ci retest

**Comment by nazrhom** [comment]
@resin-ci retest

**Comment by ZubairLK** [comment]
@resin-ci retest

**Comment by nazrhom** [comment]
@resin-ci retest

**Comment by ZubairLK** [comment]
@resin-ci retest

**Comment by ZubairLK** [comment]
@resin-ci retest

**Comment by ZubairLK** [comment]
@resin-ci retest

**Comment by ZubairLK** [comment]
@resin-ci retest

**Comment by floion** [comment]
@resin-ci retest

**Comment by floion** [comment]
@resin-ci retest

**Comment by ZubairLK** [comment]
@resin-ci retest

**Pull request merged**
